version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volume/data:/data

networks:
  default:
    name: nginx-proxy-manager
    external: true

